# 数据集配置文件
path: ../datasets/ssdd_plus  # 数据集根目录 (相对于此文件的路径)
train: train/images  # 训练图像 (相对于'path')
val: val/images      # 验证图像
test: test/images    # 测试图像

# 类别数量
nc: 3

# 类别名称
names:
  0: person
  1: bicycle
  2: car